/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumPreferencesAgeRange } from "./EnumPreferencesAgeRange";
import { IsEnum, IsOptional, ValidateNested } from "class-validator";
import { CommunityWhereUniqueInput } from "../../community/base/CommunityWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumPreferencesGenderPreference } from "./EnumPreferencesGenderPreference";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserProfileCreateNestedManyWithoutPreferencesItemsInput } from "./UserProfileCreateNestedManyWithoutPreferencesItemsInput";

@InputType()
class PreferencesCreateInput {
  @ApiProperty({
    required: false,
    enum: EnumPreferencesAgeRange,
  })
  @IsEnum(EnumPreferencesAgeRange)
  @IsOptional()
  @Field(() => EnumPreferencesAgeRange, {
    nullable: true,
  })
  ageRange?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => CommunityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CommunityWhereUniqueInput)
  @IsOptional()
  @Field(() => CommunityWhereUniqueInput, {
    nullable: true,
  })
  community?: CommunityWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumPreferencesGenderPreference,
  })
  @IsEnum(EnumPreferencesGenderPreference)
  @IsOptional()
  @Field(() => EnumPreferencesGenderPreference, {
    nullable: true,
  })
  genderPreference?: "Option1" | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  otherPreferences?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserProfileCreateNestedManyWithoutPreferencesItemsInput,
  })
  @ValidateNested()
  @Type(() => UserProfileCreateNestedManyWithoutPreferencesItemsInput)
  @IsOptional()
  @Field(() => UserProfileCreateNestedManyWithoutPreferencesItemsInput, {
    nullable: true,
  })
  userProfiles?: UserProfileCreateNestedManyWithoutPreferencesItemsInput;
}

export { PreferencesCreateInput as PreferencesCreateInput };
