/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Preferences } from "./Preferences";
import { PreferencesCountArgs } from "./PreferencesCountArgs";
import { PreferencesFindManyArgs } from "./PreferencesFindManyArgs";
import { PreferencesFindUniqueArgs } from "./PreferencesFindUniqueArgs";
import { CreatePreferencesArgs } from "./CreatePreferencesArgs";
import { UpdatePreferencesArgs } from "./UpdatePreferencesArgs";
import { DeletePreferencesArgs } from "./DeletePreferencesArgs";
import { UserProfileFindManyArgs } from "../../userProfile/base/UserProfileFindManyArgs";
import { UserProfile } from "../../userProfile/base/UserProfile";
import { Community } from "../../community/base/Community";
import { PreferencesService } from "../preferences.service";
@graphql.Resolver(() => Preferences)
export class PreferencesResolverBase {
  constructor(protected readonly service: PreferencesService) {}

  async _preferencesItemsMeta(
    @graphql.Args() args: PreferencesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Preferences])
  async preferencesItems(
    @graphql.Args() args: PreferencesFindManyArgs
  ): Promise<Preferences[]> {
    return this.service.preferencesItems(args);
  }

  @graphql.Query(() => Preferences, { nullable: true })
  async preferences(
    @graphql.Args() args: PreferencesFindUniqueArgs
  ): Promise<Preferences | null> {
    const result = await this.service.preferences(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Preferences)
  async createPreferences(
    @graphql.Args() args: CreatePreferencesArgs
  ): Promise<Preferences> {
    return await this.service.createPreferences({
      ...args,
      data: {
        ...args.data,

        community: args.data.community
          ? {
              connect: args.data.community,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Preferences)
  async updatePreferences(
    @graphql.Args() args: UpdatePreferencesArgs
  ): Promise<Preferences | null> {
    try {
      return await this.service.updatePreferences({
        ...args,
        data: {
          ...args.data,

          community: args.data.community
            ? {
                connect: args.data.community,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Preferences)
  async deletePreferences(
    @graphql.Args() args: DeletePreferencesArgs
  ): Promise<Preferences | null> {
    try {
      return await this.service.deletePreferences(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [UserProfile], { name: "userProfiles" })
  async findUserProfiles(
    @graphql.Parent() parent: Preferences,
    @graphql.Args() args: UserProfileFindManyArgs
  ): Promise<UserProfile[]> {
    const results = await this.service.findUserProfiles(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Community, {
    nullable: true,
    name: "community",
  })
  async getCommunity(
    @graphql.Parent() parent: Preferences
  ): Promise<Community | null> {
    const result = await this.service.getCommunity(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
