/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Community as PrismaCommunity,
  Preferences as PrismaPreferences,
  UserProfile as PrismaUserProfile,
} from "@prisma/client";

export class CommunityServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CommunityCountArgs, "select">
  ): Promise<number> {
    return this.prisma.community.count(args);
  }

  async communities<T extends Prisma.CommunityFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFindManyArgs>
  ): Promise<PrismaCommunity[]> {
    return this.prisma.community.findMany<Prisma.CommunityFindManyArgs>(args);
  }
  async community<T extends Prisma.CommunityFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityFindUniqueArgs>
  ): Promise<PrismaCommunity | null> {
    return this.prisma.community.findUnique(args);
  }
  async createCommunity<T extends Prisma.CommunityCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityCreateArgs>
  ): Promise<PrismaCommunity> {
    return this.prisma.community.create<T>(args);
  }
  async updateCommunity<T extends Prisma.CommunityUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityUpdateArgs>
  ): Promise<PrismaCommunity> {
    return this.prisma.community.update<T>(args);
  }
  async deleteCommunity<T extends Prisma.CommunityDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommunityDeleteArgs>
  ): Promise<PrismaCommunity> {
    return this.prisma.community.delete(args);
  }

  async findPreferencesItems(
    parentId: string,
    args: Prisma.PreferencesFindManyArgs
  ): Promise<PrismaPreferences[]> {
    return this.prisma.community
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .preferencesItems(args);
  }

  async findUserProfiles(
    parentId: string,
    args: Prisma.UserProfileFindManyArgs
  ): Promise<PrismaUserProfile[]> {
    return this.prisma.community
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .userProfiles(args);
  }
}
