/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CommunityService } from "../community.service";
import { CommunityCreateInput } from "./CommunityCreateInput";
import { Community } from "./Community";
import { CommunityFindManyArgs } from "./CommunityFindManyArgs";
import { CommunityWhereUniqueInput } from "./CommunityWhereUniqueInput";
import { CommunityUpdateInput } from "./CommunityUpdateInput";
import { PreferencesFindManyArgs } from "../../preferences/base/PreferencesFindManyArgs";
import { Preferences } from "../../preferences/base/Preferences";
import { PreferencesWhereUniqueInput } from "../../preferences/base/PreferencesWhereUniqueInput";
import { UserProfileFindManyArgs } from "../../userProfile/base/UserProfileFindManyArgs";
import { UserProfile } from "../../userProfile/base/UserProfile";
import { UserProfileWhereUniqueInput } from "../../userProfile/base/UserProfileWhereUniqueInput";

export class CommunityControllerBase {
  constructor(protected readonly service: CommunityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Community })
  async createCommunity(
    @common.Body() data: CommunityCreateInput
  ): Promise<Community> {
    return await this.service.createCommunity({
      data: data,
      select: {
        communityName: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Community] })
  @ApiNestedQuery(CommunityFindManyArgs)
  async communities(@common.Req() request: Request): Promise<Community[]> {
    const args = plainToClass(CommunityFindManyArgs, request.query);
    return this.service.communities({
      ...args,
      select: {
        communityName: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Community })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async community(
    @common.Param() params: CommunityWhereUniqueInput
  ): Promise<Community | null> {
    const result = await this.service.community({
      where: params,
      select: {
        communityName: true,
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Community })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCommunity(
    @common.Param() params: CommunityWhereUniqueInput,
    @common.Body() data: CommunityUpdateInput
  ): Promise<Community | null> {
    try {
      return await this.service.updateCommunity({
        where: params,
        data: data,
        select: {
          communityName: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Community })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCommunity(
    @common.Param() params: CommunityWhereUniqueInput
  ): Promise<Community | null> {
    try {
      return await this.service.deleteCommunity({
        where: params,
        select: {
          communityName: true,
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/preferencesItems")
  @ApiNestedQuery(PreferencesFindManyArgs)
  async findPreferencesItems(
    @common.Req() request: Request,
    @common.Param() params: CommunityWhereUniqueInput
  ): Promise<Preferences[]> {
    const query = plainToClass(PreferencesFindManyArgs, request.query);
    const results = await this.service.findPreferencesItems(params.id, {
      ...query,
      select: {
        ageRange: true,

        community: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        genderPreference: true,
        id: true,
        otherPreferences: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/preferencesItems")
  async connectPreferencesItems(
    @common.Param() params: CommunityWhereUniqueInput,
    @common.Body() body: PreferencesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      preferencesItems: {
        connect: body,
      },
    };
    await this.service.updateCommunity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/preferencesItems")
  async updatePreferencesItems(
    @common.Param() params: CommunityWhereUniqueInput,
    @common.Body() body: PreferencesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      preferencesItems: {
        set: body,
      },
    };
    await this.service.updateCommunity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/preferencesItems")
  async disconnectPreferencesItems(
    @common.Param() params: CommunityWhereUniqueInput,
    @common.Body() body: PreferencesWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      preferencesItems: {
        disconnect: body,
      },
    };
    await this.service.updateCommunity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/userProfiles")
  @ApiNestedQuery(UserProfileFindManyArgs)
  async findUserProfiles(
    @common.Req() request: Request,
    @common.Param() params: CommunityWhereUniqueInput
  ): Promise<UserProfile[]> {
    const query = plainToClass(UserProfileFindManyArgs, request.query);
    const results = await this.service.findUserProfiles(params.id, {
      ...query,
      select: {
        birthDate: true,

        community: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        fullName: true,
        gender: true,
        id: true,

        preferences: {
          select: {
            id: true,
          },
        },

        religion: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/userProfiles")
  async connectUserProfiles(
    @common.Param() params: CommunityWhereUniqueInput,
    @common.Body() body: UserProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userProfiles: {
        connect: body,
      },
    };
    await this.service.updateCommunity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/userProfiles")
  async updateUserProfiles(
    @common.Param() params: CommunityWhereUniqueInput,
    @common.Body() body: UserProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userProfiles: {
        set: body,
      },
    };
    await this.service.updateCommunity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/userProfiles")
  async disconnectUserProfiles(
    @common.Param() params: CommunityWhereUniqueInput,
    @common.Body() body: UserProfileWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userProfiles: {
        disconnect: body,
      },
    };
    await this.service.updateCommunity({
      where: params,
      data,
      select: { id: true },
    });
  }
}
